### ISSUE TITLE
false convergence (8)

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#10]
Some how gls regressions present this specific error for some combinations of species.
How to deal with that?

**Comment by caterinap** [comment]
Seriously thinking to go back to caper::pgls function..

**Comment by paternogbc** [comment]
In my simulations I also had many errors with caper::pgls and it is much slower.
Not sure what is the best. 

For me it is clear that small sample size is influencing this error. I never get error with more then 60  species.
