### ISSUE TITLE
match_data_phy

### ISSUE THREAD

**Issue by caterinap** [paternogbc/sensiPhy#103]
Problem with intra: match_data_phy does not include Vx and Vy in the dataset - if species are dropped. An error message occurs because there are different row numbers.
(for some reason I thought that we already solved this before..)

**Comment by caterinap** [comment]
Potential solution: come back to `function(data,phy)` instead of `function(formula,data,phy)`

**Comment by paternogbc** [comment]
Could you post a reproducible example here? 
Maybe we can stick with `function(formula, data, phy)` approach.

**Comment by caterinap** [comment]
Here it is:
`sieg<-read.table("~/SiegData.txt",h=T)
rownames(sieg)<-sieg$Binomial
tree<-read.nexus("~/FritzTree.rs200k.100trees.tre")
tree1<-tree[[1]]
m1<-intra_phylm(Mass_mean~BMR_Mean,Vx="Mass_SD",Vy="BMR_SD",data=sieg,phy=tree1)`

Maybe the `function(data,phy)` is of broader interest?

[SiegData.txt](https://github.com/paternogbc/sensiPhy/files/339320/SiegData.txt)

**Comment by paternogbc** [comment]
I got an Error, but: 
`str(sieg)` shows that Mass_mean has some non numeric values ("?" and "d" in three rows).
so the variable of class "factor" not numeric. 

After fixing this in original data file (not sure if the change was not introduced by linux after downloading).
and running the code I get:

> Used dataset has  681  species that match data and phylogeny
Error in phylolm::phylolm(respV ~ predV, data = full.data, model = model,  : 
  number of rows in the data does not match the number of tips in the tree.

**Comment by caterinap** [comment]
Oh, the "?" and "d" were in the original dataset, I missed those. I removed them and then it worked, I just got warnings:

> Warning messages:
1: In intra_phylm(Mass_mean ~ BMR_Mean, Vx = "Mass_SD", Vy = "BMR_SD",  ... :
  distrib=normal: make sure that standard deviation 
                                 is provided for Vx or Vy
2: In match_dataphy(formula, data, phy) :
  Some phylogeny tips do not match species in data, species were dropped from phylogeny or data
3: In `[<-.factor`(`*tmp*`, iseq, value = c(0, 0, 0, 0, 0,  ... :
  invalid factor level, NA generated
4: In `[<-.factor`(`*tmp*`, iseq, value = c(0, 0, 0, 0, 0,  ... :
  invalid factor level, NA generated

Now, I don't get you error message... find below the new version of the dataset. 

Plot of the example:
![example_intra](https://cloud.githubusercontent.com/assets/6351295/16455483/c3b5ac86-3e14-11e6-91fe-e214029ba3f5.jpeg)

[SiegData.txt](https://github.com/paternogbc/sensiPhy/files/339448/SiegData.txt)

**Comment by paternogbc** [comment]
Great! 
Now I get the same result here. 
Do you know why this warning? 
> invalid factor leel, NA generated

it is related to the class of vectors or something like it.

**Comment by caterinap** [comment]
It looks like related to the presence of NAs in the dataset if you `na.omit(sieg)` then it disappears, I don't know what it implies yet..

Anyway the "problem" of match_data_phy wasn't a problem :)

**Comment by caterinap** [comment]
There was a small mistake, problem solved!
