### ISSUE TITLE
Update the help function of samp_xxx to include note about p-values

### ISSUE THREAD

**Issue by gijsbertwerner** [paternogbc/sensiPhy#105]
Include a brief note in the help for samp_xxx that dropping species may reduce power to detect significant slopes/intercepts and may partially be responsible for a potential effect of species removal on p-values.

**Comment by paternogbc** [comment]
Should we just use your text for this?
```
#' @note Please be aware that dropping species may reduce power 
to detect significant slopes/intercepts and may partially be responsible 
for a potential effect of species removal on p-values.
```

**Comment by gijsbertwerner** [comment]
Yes, great! Have added it, slightly modified! 

Have also update help of samp_xxx a bit to include that we now print sDFs, because that wasn't mentioned yet...
