### ISSUE TITLE
Update function file names?

### ISSUE THREAD

**Issue by gijsbertwerner** [paternogbc/sensiPhy#106]
This is a very minor point, but some/mosts of the function file names in the R folder still refer to the old function names (e.g. influ_phylolm rather than influ_phylm). This of course does not at all matter for the average user, but may be confusing to those that actually will take a look at the underlying code. Should we update this?

**Comment by paternogbc** [comment]
Yes we can update file names. Good point. 
Consider a quick check about what is the best way to this with git files.

**Comment by gijsbertwerner** [comment]
I think we should be able to simply rename the current files to the new function names. Shall I just try it?

**Comment by paternogbc** [comment]
Yep :)

**Comment by gijsbertwerner** [comment]
Check. Done! It seems that everything is still working as expected :-)
