### ISSUE TITLE
Function to mutate binary data for logistic regression

### ISSUE THREAD

**Issue by gijsbertwerner** [paternogbc/sensiPhy#107]
Similar to the current intra_phylm/intra_phy_glm-functions we could also include a function to allow for randomised/mutated data for the response variable in a phylogenetic logistic regression. This could be based on the number of observations per species and the variation among them in charcter state, using binomial resampling. I am currently doing this in a project I am working on, and could implement this in a function for a future release. To be implemented later.

**Comment by paternogbc** [comment]
Great point!
Em 11/07/2016 14:00, "Gijsbert Werner" <notifications@github.com> escreveu:
