### ISSUE TITLE
Include sDFslope/intercept also in samp, clade, tree and intra? 

### ISSUE THREAD

**Issue by gijsbertwerner** [paternogbc/sensiPhy#108]
Currently in the samp/influ/etc.model.estimates we give the standardised differences for slope and intercept only in influ, but not in clade, samp, tree and intra. I suppose that probably the reason for this is that only influ_xxx contains an argument to set the standardised cut-off, whereas in the other functions it would only be an extra value to report. 

Still, to many users it may be equally or even more useful to see the standarised estimates, rather than the full ones. We could therefore consider including these too in the output, similar to in influ_xx. Downside would be that this may becoming confusing because we are 'dumping' too much information on the user?

**Comment by caterinap** [comment]
We could add it in intra and tree, but in that case the measure would be slightly different from the other functions. It would be the difference from a model using mean trait values (which is the measure that people often, but not always, use). I think it interesting, but could also be confusing?

**Comment by gijsbertwerner** [comment]
Thinking about it a bit more, I guessed this comment is most relevant to clade_xx and samp_xxx. I suppose that both of these functions share the same underlying 'philosophy' of rerunning with a reduced dataset and given some estimate for the difference with the full model. Intra/tree of course also do reruns but there is not really a model there that you can think of as the fuller or more complete model, so means make more sense. So, yes, let's not add in tree/intra. 

Anyway, when going over the examples of clade, samp and influ I realised there was this difference, and thought we could consider standardising the output a bit more. But I am fine with as it is now as well. What do you think @paternogbc ?

**Comment by paternogbc** [comment]
I also had the same feeling before, but I am fine with the way it is now because intra_xx and tree_xx don't really have a "full model" and I agree with @caterinap that using the "mean" as the full model could cause confusion.

**Comment by gijsbertwerner** [comment]
No, I completely agree: for intra and tree this approach makes less sense.

I was referring more to standardising the output among samp, clade and influ, so that they all give a sDF in the output, not only influ. But as a I said, either is fine with me :-)

---------------------------------------------------
Dr. Gijsbert Werner
Newton Fellow
Department of Zoology
University of Oxford
South Parks Road<x-apple-data-detectors://1/1>
Oxford<x-apple-data-detectors://1/1>
OX1 3PS<x-apple-data-detectors://1/1>
United Kingdom<x-apple-data-detectors://1/1>

On 13 Jul 2016, at 20:40, Gustavo Paterno <notifications@github.com<mailto:notifications@github.com>> wrote:


I also had the same feeling before, but I am fine with the way it is now because intra_xx and tree_xx don't really have a "full model" and I agree with @caterinap<https://github.com/caterinap> that using the "mean" as the full model could cause confusion.

**Comment by paternogbc** [comment]
Ahh I see, sorry @gijsbertwerner 

I think the original reason why I didnt include the sDF in clade_xx was because the standardized difference might not be so informative for few clades. Lets say we have three families to consider as "clades", you have to calculate the the standard deviation out of only three numbers. I dont see a real problem with this,  I am just not 100% sure it is informative (actually when the number of clades is high it is a interesting metric).  
So we could do it. To include in samp we could do it per break-interval?

**Comment by gijsbertwerner** [comment]
Ahh of course, I hadn't thought about the fact that there often is only a few members per clade/group. Yes, makes sense to not do it then, let's leave out. 

I have taken the liberty to include the sDFs for samp, however. I have (i) included them in as a column in the samp.estimates block and (ii) following @paternogbc 's suggestion have included the average sDF per break in the sign.analyis block in commit https://github.com/paternogbc/sensiPhy/commit/a0c849ff6c8b0806b35908caee1f77dc6a5557b6
See what you think, and feel free to reverse. We could also keep (i), but not (ii). The advantage of (ii) is however that it may also to some extent address https://github.com/paternogbc/sensiPhy/issues/93

**Comment by paternogbc** [comment]
Great, 
I think we could keep both for samp_xxx ;)

**Comment by gijsbertwerner** [comment]
Perfect! :-)
