### ISSUE TITLE
intra_phylm error message

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#109]
Found this Error message running the following example:

```
library(sensiPhy)
data("alien")
fit <- intra_phylm(homeRange ~ adultMass, data = alien$data, 
                  phy = alien$phy[[1]], Vx = "SD_mass" ,times = 100, 
                  x.transf = log, y.transf = log)
```

```
Error in phylolm::phylolm(respV ~ predV, data = full.data, model = model,  : 
  number of rows in the data does not match the number of tips in the tree.
Além disso: Warning message:
In x.transf(full.data$predV) : NaNs produzidos
```

The same regression dont give error with influ_xxx

```
fit <- influ_phylm(log(homeRange) ~ log(adultMass), data = alien$data, 
                   phy = alien$phy[[1]])
```
Any ideias?

**Comment by caterinap** [comment]
match_data_phy should avoid this error..

**Comment by paternogbc** [comment]
Yes exactly.. I though that we had fixed it.. ;/ 
When you increase the number of simulations I also got this type:

```
Error in phylolm::phylolm(respV ~ predV, data = full.data, model = model,  : 
  number of rows in the data does not match the number of tips in the tree.
```

**Comment by caterinap** [comment]
ok, I am on it!

**Comment by caterinap** [comment]
Found the problem: the function picks a random value in mean+-SD, when SD exceeds the mean then the function might pick a negative, or null value. If these values are logged then it produces NAs, normal. Theoretically that is fine but having negative (or null) trait values does not make much sense.. Some potential solutions:
- limit the values to positive & non-null (best for basic users)
- ignore the iteration when there are negative/null values in the dataset and go to the next, but throw a warning (best for advanced users)
Any preference or additional suggestion?

**Comment by paternogbc** [comment]
Great @caterinap !!!!

I would simple repete the iteration when there are negative values. This would keep the same amount of
simulations at the end (= to times) and avoid including more warnings. I would include a short note on details explaining that traits with high intraspecific variance could yeld negative values and this will be ignored. 

What to do when traits have negative values naturally?

**Comment by caterinap** [comment]
@paternogbc that would be good..  I tried but you cannot really avoid a "while" loop, which is not ideal and can slow down the process quite a lot (+risks of infinite loops).

The problem with negative values is not the model itself (which runs with whatever value) but the log (or log10 or sqrt..) transformation that create NA's in the dataset and then there is a mismatch with the phylogeny, we could use match_dataphy again but there would be different numbers of species in each iteration (-->bad).

The best I found for the moment is:
 if SD>=mean and the user wants a log, log10, sqrt.. (others?) stop the function and tell the user to use a log(x+SD) transformation instead of log(x) - or tell him to use the argument "avoidneg=T" (that would do this or just limit the random value from 0 to mean+SD).

I am not very happy with this solution yet, it is not super elegant, so I am going to take some more time to think about it.. in the meanwhile any other idea is very welcome!
(hope my explanation is clear..)

**Comment by paternogbc** [comment]
Hey @caterinap,

I agree, no while loop, no match_dataphy() twice. =)

One point, SD does not need to be higher than the mean to yield negative values, so this will happen in other situations (given a sufficient amount of repetitions), right? So I would not use the SD>=mean as indicator. 
Perhaps a other indicator might be good... not sure but maybe if  mean - 2*SD =< 0? 
 
The problem with avoiding negative values is that the distribution of randomized values will be skewed, since part of the distributions is being restricted. 

I would say we keep as it is and when negative values generate NaNs we might skip the simulation  
and print a warming at the end saying that X simulations were ignored due to NAs values, and suggest to transform their data as you said.  
Further we could explain this issue in more details in the help (as a Warning section of intra_xxx).

I will be thinking more about it... 
;)

**Comment by paternogbc** [comment]
But it is quite complicated since SD is species-specific and one species might have a very high SD and the hole simulation is ruined...

**Comment by gijsbertwerner** [comment]
Hmm tricky problem @caterinap . I would also be inclined to say that @paternogbc 's solution to skip those simulations where NAs are generated and print a warning. Then people can always manually set a higher number and rerun, if they want to ensure the original number was met. 

If there is one/a few species causing this could we catch those species names and print them? That way users can examine these species see if there is something wrong with the data point and consider rerunning while excluding that species? 

And yes, let's certainly include a warning/explanation in the help section! We should explain why people can get this result :-)

**Comment by caterinap** [comment]
Cool! I also like this solution of skipping the simulations and let the user being responsible of his transformation choice. It is easy to do and if we find a better solution we can still come back.
So for the moment: skip the simulation, identify the "problematic" species, print a warning with the nb of failed simulations and the name of the species that cause the problem + explain all this in the help.

**Comment by paternogbc** [comment]
Perfect :))
