### ISSUE TITLE
Error in intra_phyglm?

### ISSUE THREAD

**Issue by gijsbertwerner** [paternogbc/sensiPhy#110]
I was playing around with intra_phyglm a bit, and was trying to run this example (modified from samp_phyglm examples): 

set.seed(6987)
phy = rtree(150)
x = rTrait(n=1,phy=phy)
x_sd = rnorm(150)
X = cbind(rep(1,150),x)
y = rbinTrait(n=1,phy=phy, beta=c(-1,0.5), alpha=.7 ,X=X)
dat = data.frame(y, x, x_sd)
# Run phylogenetic regression accounting for intraspecific variation:
intra <- intra_phyglm(y~x,Vx = x_sd,data = dat,phy=phy,distrib = "normal")

and get this error: Error in .subset(x, j) : only 0's may be mixed with negative subscripts

I have debugged a bit, and am pretty sure that the issue is in lines 90-91, because it doesn't correctly subset the full-data frame. 

I might try and work on this a bit, but feel free to take a look too :-)

**Comment by gijsbertwerner** [comment]
Ok, that was very easy. This was my own mistake in not putting x_sd between parentheses. Sorry!

**Comment by gijsbertwerner** [comment]
However, I did find another problem, because if I do change that and rerun, I get this error:

Error in `[.data.frame`(full.data, , c("respV", "predV")) :  undefined columns selected

I think this is because the 'respV' in line 128 should be 'resp1', don't you think @caterinap ?

**Comment by caterinap** [comment]
Thanks! Yep indeed the problem was at L 128, respV actually was not required at all. If you try your code again it should work now, but watch out, `rnorm` also produces negative values, and this is not going to work to simulate a standard deviation (and crashes) :-)
fixed in commit  2a8a1a7

**Comment by gijsbertwerner** [comment]
Great Caterina! I have taken the liberty of adding the example (slightly modified so rnorm does not generate negative values anymore) to the function help, because I thought it's best if all functions have at least one working example :-)

**Comment by caterinap** [comment]
Great!! thanks!
