### ISSUE TITLE
Phylogenetic signal in missing data

### ISSUE THREAD

**Issue by caterinap** [paternogbc/sensiPhy#112]
Hey,
I'm working on the function to calculate phylo signal in missing data.
The function basically does this:
1. calculate and print % of NAs per trait
2. recode traits into binary (1=NA, 0=nonNA)
3. match data and phylogeny with `match.data.phy`
4. call `caper::phylo.d` [https://cran.r-project.org/web/packages/caper/vignettes/caper.pdf] to calculate phylo signal

Question: should I stop before step 4 and just produce an object that people can use to feed `phylo.d` or should I go until the end? Any preference?

**Comment by paternogbc** [comment]
Nice Cat!
I think you should go all the way to step 4.

Em 9 de set de 2016 07:16, "caterinap" <notifications@github.com> escreveu:

**Comment by gijsbertwerner** [comment]
Agreed, let’s finish it if we are setting everything up anyway :-) Great work!

-----------------------------------------
Dr. Gijsbert Werner
Newton Fellow
Department of Zoology
University of Oxford
South Parks Road
Oxford
OX1 3PS
United Kingdom




On 9 Sep 2016, at 11:21, Gustavo Paterno <notifications@github.com<mailto:notifications@github.com>> wrote:

Nice Cat!
I think you should go all the way to step 4.

Em 9 de set de 2016 07:16, "caterinap" <notifications@github.com<mailto:notifications@github.com>> escreveu:

**Comment by caterinap** [comment]
Ok, I created a new branch (SensiPhy.0.5.0.9000) and added the new function (miss,phylo.d). See if you like it!
