### ISSUE TITLE
Interaction between uncertainty types

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#121]
Write to general function to test the interaction between different sources of uncertainty.
1. inter_tree
* tree vs influ
* tree vs clade
* tree vs samp

2. inter_intra
* intra vs influ
* intra vs clade
* intra vs samp

**Comment by paternogbc** [comment]
One question: where should we put the tree vs intra interaction?

**Comment by gijsbertwerner** [comment]
In both, I guess, and then see who gets there first :-)

**Comment by caterinap** [comment]
Yep, I still have an old version of code that was doing that, I can update it with new functionalities and we can start from it.

**Comment by paternogbc** [comment]
So we would implement the same function in both? I have no problem with that actually.

**Comment by paternogbc** [comment]
So, lets start with **_phylm** and then when we finish and check we just duplicate to **_phyglm**, right?

**Comment by caterinap** [comment]
Other possibility would be to have a single function with 3 arguments. 
- `tree=TRUE/FALSE`, 
- `intra=TRUE/FALSE`,
- `other=NULL` that could be _influ_, _clade_ or _samp_.
But that would imply having three interactions 
Or to avoid it we can add:
If `other!=NULL` then `tree=TRUE & intra=TRUE` gives an error
This would not allow all pairwise interactions (e.g. influ with clade) but would avoid multiplying functions.
Just a thought :)

**Comment by gijsbertwerner** [comment]
Great idea, Caterina! We could even simplify this to setting an initial argument which will only accept tree/intra, i.e.:
- `main_uncertainty = tree/intra`
- `other = NULL` and could be influ/clade/samp 
Would potentially solve three-way interactions, and would retain a single general function. I would still also be ok with just having two separate functions for tree and intra, or something along these lines.

**Comment by paternogbc** [comment]
great ideas guys! =)
Adding to that I think we would keep the two separated functions **inter_tree** and **inter_intra** (to avoid too much confusion and to keep both functions simple to use and understand).
Then we include only one argument:

`uncertainty = samp/clade/influ/tree/intra`

**Comment by caterinap** [comment]
Ok and if we still want one instead of two we can use  `other ` = influ/clade/samp/tree/intra (so we can have the tree/intra interaction). And forbid `main_uncertainty == other`. But probably easier to start with two functions.

**Comment by paternogbc** [comment]
I think for the user is less confusion to choose between two lines of interaction. With tree and with intra. 
Because the argument naming also get hard to explain if we have only one. 
So I would go for two, and this will actually matter only in the end right? because we need to build each of the functions isolated first, then we call them with the general function inter_tree (uncertainty = "clade"), for instance could call the hiden function inter_tree_clade().

**Comment by paternogbc** [comment]
Just one more point. Lets put some ideas out about the type of output (summary and plot) that would come from these interaction functions for each of the different interactions. I will create a issue focused on that so we can include graphs and proposed summary tables while we develop them. This would make discussions and decision more easy I guess.

**Comment by gijsbertwerner** [comment]
Yes, these are all great points Gustavo. Let's start with separate functions and two ones for the user, also to facilitate debugging. We can letter consolidate in a single one as discussed above, if we feel that helps the user. 

I have started an 'interactions' branch. I think I will call the function interaction_intra_xxx for now, rather than inter_intra etc, because I worry that with 'inter' and 'intra' in the same function name people will think 'inter' refers to interspecific (as opposed to infraspecific), but we mean interaction... We can always change.

**Comment by paternogbc** [comment]
Hey @gijsbertwerner , that sounds great. So, the idea would be to start creating small independent functions for each specific task (eg. interaction_intra_clade; interaction_tree_clade, interaction_intra_samp, etc). This wont be exported to the user. But two or one general function for the interactions will call them based on the arguments (uncertainty = xxx). This will help us to build them more isolated and keep track of problems when we do tests (we will know where to look when we have problems ;)
