### ISSUE TITLE
Output: influ_physig

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#124]
# Plots
### Estimated values
![image](https://cloud.githubusercontent.com/assets/9639481/25268912/d715959e-267a-11e7-80ea-655ff86976d8.png)

### P values
![image](https://cloud.githubusercontent.com/assets/9639481/25269077/7457d196-267b-11e7-9233-55b00d652fd7.png)

Just use the same graphs for Lambda. I think including the 0.05 Vertical line will be of good help to see if there is any change in significance when removing single species. So this two simple graphs show the influence of species removal on precision and significance.

**Comment by gijsbertwerner** [comment]
Cool, I like it!

**Comment by paternogbc** [comment]
## Example for Summary:
```
$`Influential species for k`
[1] "Camelus_bactrianus"  "Equus_hemionus"      "Capreolus_capreolus" "Ovibos_moschatus"   

$`K Estimates`
      Species removed        K       DFk Change(%)  Pval
1  Camelus_bactrianus 2.003153 0.2459327      14.0 0.001
2      Equus_hemionus 1.990021 0.2328016      13.2 0.001
3 Capreolus_capreolus 1.876729 0.1195095       6.8 0.001
4    Ovibos_moschatus 1.873862 0.1166423       6.6 0.001

$`Influential species for lambda`
[1] "Axis_axis"     "Axis_porcinus"

$`Intercept Estimates`

  Species removed Lambda DFlambda   Change(%) Pval
1       Axis_axis  0.001 1.005018 0.003247118  0.3
2   Axis_porcinus  0.001 1.005018 0.003247118  0.3
```

## Example for Plot
![image](https://cloud.githubusercontent.com/assets/9639481/25307559/2c435898-27a3-11e7-8a8a-16ce2ef5a61a.png)

I think I will give the option for the user to choose between "k" or "lambda" instead of providing both at the same time. This can be a bit time consuming for large datasets.

**Comment by gijsbertwerner** [comment]
Nice visualisation, and I also like the calculation of influential species for lambda/K.

**Comment by paternogbc** [comment]
I have totally finished this function now with summary and plot methods implemented in the branch.
If you would like to test later, here it go.
influ_physig: https://github.com/paternogbc/sensiPhy/blob/phylo_signal/R/influ_physig.R
