### ISSUE TITLE
Small fix to match_dataphy (no tip labels on data)

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#126]
When the user provides a data.frame without species names, check if data and phylogeny has the same number of rows. If it does, instead of printing an error and stoping the function, print a warning to the user telling that the function is assuming that data and phylogeny are in the same order.
If they have different numbersof rows, then stop the function with the usual warning message:
```
Error in match_dataphy(formula, data, phy) : 
  No tips are common to the dataset and phylogeny, 
        Please check if row names of your dataset contain species/tip names
```

See `phytools::matchDatatotree` and use the same approach.

```
if(is.null(names(x))){
		if(length(x)==length(tree$tip.label)){
			print(paste(name,"has no names; assuming x is in the same order as tree$tip.label"))
			names(x)<-tree$tip.label
		} else

stop(paste(name,"has no names and is a different length than tree$tip.label"))
```

**Comment by gijsbertwerner** [comment]
Great addition!

**Comment by caterinap** [comment]
Gustavo, are you working on this now? I could add it at the same time I fix the other bug. Maybe in a new branch?

**Comment by paternogbc** [comment]
hey @caterinap 
I am not working on this. Just created the issue so we dont forget =)
Great. Perhaps you can just add this and fix the bug in the master branch and make one commit about it. 
If you dont change the output structure of the function and just include I think its ok to work on the master =).  Could you also add a line sensiPhy 0.7 and include what has changed inside the NEWS file at root directory.

**Comment by caterinap** [comment]
ok! will do! thanks
