### ISSUE TITLE
Output: clade_physig

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#127]
I have developed the function `clade_physig`. It simple repeats the approach from `clade_phylm` including the randomization test (although I am not sure if this makes too much sense).

One very intersting thing is that K is very sensitive to sample size and removing species seems to always reduce K estimate. It appears to be a general trend as I tested with different datasets and it usually lower the value of K estimate when a reduced dataset is used. You can clearly see this pattern on the graphs bellow where the null distribution estimates much lower values for K, although some clades removal can increase K estimate even when removing species. This seems a very nice point to explore more later.
So when you remove related species from the sample, you can increase or reduce K estimate (differene between red and black line), but when you remove a random set of species from the sample (null distribution) you usually reduce k estimate (yellow bars). 

## Plot output:
Red line is the estimate of K without the clade and the black line is the estimate of k with the full data.
![image](https://cloud.githubusercontent.com/assets/9639481/25313933/9323f748-2839-11e7-8646-ae02342e9853.png)

## Summary output:
```
clade.removed N.species         k          DFk Change (%)  Pval m.null.slope Pval.randomization
3         Hylidae       161 0.4317358  0.065725866       18.0 0.001    0.2019730                  0
2   Centrolenidae        36 0.3148883 -0.051121639       14.0 0.001    0.2128271                  0
1       Bufonidae        49 0.4128964  0.046886516       12.8 0.001    0.1811373                  0
6         Ranidae        38 0.3439581 -0.022051838        6.0 0.001    0.1873398                  0
5 Leptodactylidae        39 0.3831670  0.017157066        4.7 0.001    0.2062599                  0
4    Hyperoliidae        33 0.3572937 -0.008716179        2.4 0.001    0.2143961                  0
```

**Comment by paternogbc** [comment]
## Summary output:
```
clade.removed N.species         k          DFk Change (%)  Pval m.null.slope Pval.randomization
3         Hylidae       161 0.4317358  0.065725866       18.0 0.001    0.2019730                  0
2   Centrolenidae        36 0.3148883 -0.051121639       14.0 0.001    0.2128271                  0
1       Bufonidae        49 0.4128964  0.046886516       12.8 0.001    0.1811373                  0
6         Ranidae        38 0.3439581 -0.022051838        6.0 0.001    0.1873398                  0
5 Leptodactylidae        39 0.3831670  0.017157066        4.7 0.001    0.2062599                  0
4    Hyperoliidae        33 0.3572937 -0.008716179        2.4 0.001    0.2143961                  0
```

**Comment by gijsbertwerner** [comment]
Cool, Gustavo, this is really nice. I suppose we could look a bit in the literature a bit to check if the sensitivity of the K metric to random species removal has been described in the literature somewhere. If not, we could raise it as an interesting result/discovery from creating the package, although it might not work great with the flow of the ms.

**Comment by paternogbc** [comment]
I think this is worth a deeper investigation with a wide range of datasets and simulations before it can be proven right. If it is, this would be (1) A nice discovery and (2) a strong justification to use sensiPhy when reporting results of phylogenetic signal in papers. Regarding the 2 point, it might be valuable to just mention that on the manuscript but we need to think clear if this is not too much of deviation from the paper goal. I would rather use sensiPhy to test this hypothesis and write a new paper later if initial tests shows this pattern is really holding. This could be a nice paper investigating systematically the effect of uncertainties on phylogentic signal estimations and comparing between lambda and k (which was never really done until now, at least that I am aware of).

**Comment by paternogbc** [comment]
The lower k estimates was a small bug with the function, sorry for the confusion. It is not a pattern. I was thinking this was way too weird. I will update the fixed graphs/summary soon.

**Comment by paternogbc** [comment]
Correct plots and summary:
![image](https://cloud.githubusercontent.com/assets/9639481/25315622/631d54da-2858-11e7-894a-63ca42a0666c.png)

```
clade.removed N.species         k          DFk Change (%)  Pval m.null.slope Pval.randomization
3         Hylidae       161 0.4317358  0.065725866       18.0 0.001    0.3924587               0.19
2   Centrolenidae        36 0.3148883 -0.051121639       14.0 0.001    0.3726446               0.00
1       Bufonidae        49 0.4128964  0.046886516       12.8 0.001    0.3745087               0.07
6         Ranidae        38 0.3439581 -0.022051838        6.0 0.001    0.3759994               0.00
5 Leptodactylidae        39 0.3831670  0.017157066        4.7 0.001    0.3719169               0.24
4    Hyperoliidae        33 0.3572937 -0.008716179        2.4 0.001    0.3737685               0.17
> 
```

**Comment by paternogbc** [comment]
Same approach for lambda:

![image](https://cloud.githubusercontent.com/assets/9639481/25315851/4e2c0c8e-285c-11e7-860f-5ef0aac14084.png)

```
clade.removed N.species    lambda     DFlambda Change (%)         Pval m.null.slope Pval.randomization
1       Bufonidae        49 0.9681979  0.010888841        1.1 4.509832e-67    0.9587051          0.2000000
2   Centrolenidae        36 0.9507017 -0.006607363        0.7 1.882720e-50    0.9596983          0.1333333
6         Ranidae        38 0.9505952 -0.006713856        0.7 1.028657e-63    0.9562054          0.1333333
4    Hyperoliidae        33 0.9532268 -0.004082251        0.4 1.569421e-61    0.9594362          0.2333333
3         Hylidae       161 0.9598055  0.002496454        0.3 4.789549e-49    0.9704945          0.7666667
5 Leptodactylidae        39 0.9549738 -0.002335218        0.2 2.234784e-62    0.9592175          0.3333333

```
