### ISSUE TITLE
Small adds and checks to do before CRAN

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#134]
1. Include `...` in all phylosig functions.
2. Include `...` in all phylolm and phyloglm functions?
3. change the `xxx_model_estimates` output to `sensi_estimates` **DONE**
4. Check all examples 
5. Check man files
6. change 'object' to 'x' inside sensi_plot functions. **DONE**
7. Include FULL data estimates on summary functions (clade, influ, samp)
8. Add print methods for all new functions added on v0.7
9. Change the way the Value output of all functions are presented in the help files. Use * to illustrate the conlumn names of the main `xxx_model_estimates` data.frame.
10. Change "return(p1)" to "print(p1)" in sensi_plot function to avoid messages. **DONE**
11. Split summary table (slope/intercept) samp_phylm() and use the exact same struture to samp_physig 
12. Check all class names and standardize between functions. (matbe use call() to match instead of summary and plot methods).
13. Check all sDIFestimate calculations and formula (loops ect)
14. Check "trait" names on physig functions,   `names(trait)  <- rownames(full.data) `
15. Add error check: `if  ((model == "trend") & (ape::is.ultrametric(phy))) stop("Trend is unidentifiable for ultrametric trees., see ?phylolm for details")` in all `phylolm `functions (including interactions)  **DONE**
16. Add  `...` in all `match_dataphy` functions **DONE**
17. Add `@import ape phylolm` in functions documentation? (present in samp_phylm but not everywhere)
18. Change full model/reduced model into full data/reduced data (especially in plots)

**Comment by caterinap** [comment]
FYI I added few points by editing your comment Gustavo

**Comment by caterinap** [comment]
Given that we change all DFslope into DIFestimate I am also changing all "slope" into "estimate".
