### ISSUE TITLE
Output: clade_physig

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#136]
Hey Guys, I just finished this approach. Showing the summary and sensi_plot examples below.
You think is ok?

## Summary
```
$`Full data: K phylogenetic signal estimate`
          Trait N.species estimate  Pval
1 Log_adultMass        95 1.758589 0.001

$`Summary by clade removal`
    clade.removed N.species estimate          DF Change (%)  Pval m.null.slope Pval.randomization
3 Cercopithecidae        32 1.345703 -0.41288631       23.5 0.001     1.458768              0.301
2         Cebidae        19 2.066756  0.30816702       17.5 0.001     1.582644              0.004
1  Callitrichidae         9 1.951283  0.19269432       11.0 0.001     1.679450              0.012
4       Lemuridae         8 1.833868  0.07527902        4.3 0.001     1.685716              0.074
```
## sensi_plot

![image](https://cloud.githubusercontent.com/assets/9639481/25906226/4ed2fd14-35a4-11e7-92c3-f8674f8cd76f.png)

**Comment by caterinap** [comment]
I like it, very nice ans super clear and self-explanatory!
Maybe m.null.slope should follow the same name type as estimate and be called m.null.estimate. Also DF is usually used for degrees of freedom so maybe rename it a well?

**Comment by gijsbertwerner** [comment]
Wow, so cool! Really like it! Yes, I agree with Caterina, let's standardise slope/estimate (probably stick with 'slope'?). Really nice!

**Comment by paternogbc** [comment]
Nice guys, thanks =)

I think we should keep estimate for most functions because it is more clear. And the summary and plot can grab what method was used (K or lambda) and print the correct name on graphs and summary tables names. 

```
$`Full data: K phylogenetic signal estimate`
          Trait N.species estimate  Pval
1 Log_adultMass        95 1.758589 0.001
```
If the user runs the code with "lambda" signal, it will print `Full data: lambda phylogenetic signal estimate` 
Then the other rows can be simple estimate.

For the DF, I totally agree. What about DFestimate. And yes, the m.null.estimate is much better.

For the regression functions I am not sure yet... To use slope on the phylogenetic signal function might be confusing, and using estimate on the regressions is a good approach but we have slope and intercept.
So lets think more and we standardize at the end?

I will use the estimate for the physig functions and later we decide if and how we put everything together.
It is easier to change in batch =)
