### ISSUE TITLE
Output: samp_physig

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#138]
See what you think about summary and sensi_plot. Just very similar approach of the samp_phylm.
=)
## Sumary for K
```
  % Species Removed % Significant K Mean Change (%)    Mean sDF
1                11             100           6.382 -0.04307342
2                20             100           8.579  0.01135268
3                31              99          15.517  0.28118494
4                40              98          20.307  0.49557213
5                51              86          18.424  0.36366730
```
## Plot for K
![image](https://cloud.githubusercontent.com/assets/9639481/25916597/7a1dab42-35c5-11e7-88ef-89b343785a9e.png)
## Summary for lambda
```
  % Species Removed % Significant lambda Mean Change (%)   Mean sDF
1                11                  100           0.154 0.06686468
2                20                  100           0.449 0.24203487
3                31                  100           0.851 0.50185620
4                40                  100           1.173 0.53759807
5                51                  100           1.521 0.68674816
```

## Plot for lambda
![image](https://cloud.githubusercontent.com/assets/9639481/25916614/8ae7ec76-35c5-11e7-9190-b45d9c9f7186.png)

**Comment by caterinap** [comment]
Looks very nice! Just sDF is not self-explanatory to me, but it's a detail!

**Comment by paternogbc** [comment]
Nice, sDF is the standardized difference in estimate. it is not so clear I agree. Perhaps, sDFestimate ?

**Comment by caterinap** [comment]
sDifEstimate? It's just that when I see DF I think about degrees of freedom :) but maybe it's only me!

**Comment by paternogbc** [comment]
No... you are right. Naming can get confusing. I like sDfifEstimate / sDifSlope etc.
If @gijsbertwerner also agree I can change this all the hole package to standardize.

**Comment by gijsbertwerner** [comment]
Yes, great, let’s do!

---------------------------------------------------
Dr. Gijsbert Werner
Newton Fellow, Department of Zoology
Junior Research Fellow, Balliol College
University of Oxford

Balliol College
Broad Street
Oxford
OX1 3BJ
United Kingdom



On 11 May 2017, at 10:17, Gustavo Paterno <notifications@github.com<mailto:notifications@github.com>> wrote:


No... you are right. Naming can get confusing. I like sDfifEstimate / sDifSlope etc.
If @gijsbertwerner<https://github.com/gijsbertwerner> also agree I can change this all the hole package to standardize.
