### ISSUE TITLE
Output naming standards

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#140]
# 1 

We must decide how to name the raw difference in summary and plot methods (now is DF) and the standardized difference sDF. (e.g. DFslope; sDFslope, etc).

Another possibility is Dif  / sDif (ex. Difslope; sDifslope; Difestimate; sDifestimate)

# 2
Change return list samp.model.estimates to sensi.estimates to apply to all future function and
not only phylogenetic regression models. 
 
# 3

After we finish all the implementation of new features I must check and update the documentation
from "reduced model" to "reduced data" which is more accurate term for the approach we use.

**Comment by caterinap** [comment]
Maybe DIFslope/stdDIFslope (or sDIFslope)? Don't have any preference between "slope" or "estimate" (except that slope is shorter :).

**Comment by paternogbc** [comment]
Great I like DIFslope and sDIFslope. But for the phylogenetic signal I will keep estimate because I find slope confusing for K or lambda statistics, right? And I will always include which method was used (lambda or K) so the user can be sure what does estimate means on the table.
