### ISSUE TITLE
interaction functions for phylogenetic signal

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#142]
hey Guys I am implementing interaction functions for the physig functions.

I started with `interaction_tree_influ_physig()`.
So just run a usual leave-one-out deletion for each tree. 

With this we could generate a summary showing the Influential species based on the average value of sDIFestimate (as Gijsbert had implemented)

For this I would simple test which species has the median (or the mean) sDIFestimate higher then the cutoff. These species are in average the most influential (statistically) among all trees.
What do you think about this "test" using the average/median? 

For the sensi_plot I would provide a graph with the tree number on X and the raw estmate of K or lambda on Y. This would give a nice idea of the tree effect on estimates but also shows the influence  of species removal. 

Below you can find a trial for this approach where red color represent species with sDIF higher then the cutoff.
![image](https://cloud.githubusercontent.com/assets/9639481/26065978/cdca5a46-3995-11e7-996a-0854f4d8a646.png)

But we could also just leave without pointing out species that has high sDIF values.
![image](https://cloud.githubusercontent.com/assets/9639481/26066106/29c4ba9e-3996-11e7-99d3-320c51efc8a4.png)

You can see on these graphs that the trees 28, 74 and 37 greatly reduces the K estimate. 

Maybe this type of plot could be useful for people really trying to understand what is the tree influence of the estimates and not only averaging the estimated values between all simulations, which is what we are doing on the tree and intra functions.

**Comment by caterinap** [comment]
Wow! That looks very cool! I think the one showing the red dots is nicer, although we don't know if it's the same species that have high sDIF values across trees. Yes with this approach we can really know which are the trees that cause the variation that we see in "tree" functions.

**Comment by paternogbc** [comment]
Yep! That is true we could plot in red the species that are sDIF > cutoff for each tree instead of plotting the species that are on average. Then it would be correct for the graph. And the information about which species is more influential on average will be on summary. So I think it might work nice.

We could also think about implementing this graphs for the tree functions. =)

**Comment by caterinap** [comment]
> We could also think about implementing this graphs for the tree functions. =)

Yep, would be cool! I guess that it would be a two steps thing, or 2 different questions:  (i) you want to see if your relationship is affected by phylo uncertainty, if not -->cool! (ii) [if yes then] you want to see which are the "problematic/different trees". So maybe two different plots?

Also, just thinking, if you have more than 30/40 trees it might be difficult to read. I have not looked at the code so maybe you already have it, but if not you can add an argument `ntrees=` to set the number of trees to plot. I guess that you order the trees according to their estimate mean value?

**Comment by caterinap** [comment]
Quick question. In this case, do you set times.tree=times.influ ? I just realized that Gisjbert kept a unique `times ` in his intra_influ functions, which might work fine with `intra `functions. But for interactions with `tree `functions I would give the user the possibility to have a different number of repetitions for _n_ trees and _m_  randomizations (for clade) or _m_ random samples (for intra), etc. Having them separate allows the user to disentangle the two things. But of course it complicates things :)

**Comment by paternogbc** [comment]
I agree! _n_ trees and _m_ intra randomization should work fine. I think it does not complicate too much.
And if the user has few trees for instance but want to run the analysis with intra variation he could still do 500 randomization for each of the n trees he has. So I think we should keep this for all other tree and intra functions.

**Comment by paternogbc** [comment]
Yes I am ordering the three according to the mean estimate. And yes, after 30 you get problems visualizing. Not sure what is the best solution... So if the user choose less trees to plot, which one should I plot? 
What about the user proving a vector with the three number he wants to plot?

Check out forr 100 trees, 
![image](https://cloud.githubusercontent.com/assets/9639481/26099748/041d5972-3a2c-11e7-855b-0e436a66239e.png)

**Comment by caterinap** [comment]
The interesting ones are actually the ones deviating a lot from the rest. I am not sure that people know the tree numbers of their multiphylo files (which in many cases are automatically generated).
Maybe set the maximum to 30 (upper limit of visualisation) and have several choices:
- plot the 15 first and 15 last trees (ordered by mean estimate)
- plot the first 30
- plots the last 30
- plot a given interval (e.g. from 20 to 50)
But if people know their tree numbers and want to plot a specific one it is not optimal.. And I also think that it is nice to see **all** the trees (like you show above) to see how many of them deviate and then choose where do you want to "zoom"... What about having three methods? Print all, print interval, print single? Maybe too complicated.. :/

**Comment by paternogbc** [comment]
Ok! The last option sounds nice! Three methods. You not be so hard. And the user can check the general pattern and see all trees but also check specific trees or intervals.
Thanks ;)

**Comment by paternogbc** [comment]
Look the p-value for the phylogenetic signal between all trees:
![image](https://cloud.githubusercontent.com/assets/9639481/26102611/0be4de78-3a36-11e7-9606-b525f4b2f055.png)

**Comment by paternogbc** [comment]
# One tree histogram.
![image](https://cloud.githubusercontent.com/assets/9639481/26102800/fb6ce382-3a36-11e7-9f1a-a6f82b13da7a.png)

**Comment by caterinap** [comment]
> Look the p-value for the phylogenetic signal between all trees

WOw! That sounds like an interesting example!

**Comment by gijsbertwerner** [comment]
Wow this is really cool! Such nice graphics! I really like the plot with the trees and the red dots indicating outliers. It seems to me that it would be best to label the species in red, and ideally we would allow the user to set if he/she wants to (1) label the influential one within each tree, or (2) the average most influential ones throughout. As Caterina rightly points out, I think for most users it will be a two-stage process, first you want to find out the second question, and if there appears to be something going on then there, you then dig down deeper into specific trees. Perhaps have the second as default and the first as an option?

**Comment by gijsbertwerner** [comment]
That P-value example does look like a really nice example! Would work well in the documentation (or perhaps even paper)!
