### ISSUE TITLE
interactions with samp functions

### ISSUE THREAD

**Issue by caterinap** [paternogbc/sensiPhy#144]
How to summarize the results for the interactions involving `samp `functions (tree-samp and intra-samp)?
We could have:
- histograms showing estimates, intercepts, pvalues for all simulations and the usual red line for "true" model (which would be the mean across trees and full data)
- % of significant slopes for all the trees (or just a mean+/- CI)
Any idea is welcome :)

The other problem with samp is that the total number of repetitions can be high:  i.e. tree (or intra) * number of random deletions * % of species deleted.

**Comment by paternogbc** [comment]
Nice Cat. 

I think would be also important to keep some graphs with the % of removed species on the x variable. Because this informative for the user to state in the paper, "we can remove 40% of the data without changing more then 5% on the slope, even considering phylogenetic uncertainty.

Yes, the function will take ages for large datasets. But we could warn this on the function details and online guide. So user can and the progress and decide to wait.

**Comment by gijsbertwerner** [comment]
Perhaps I haven't thought this trough far enough, but could we not have as the basis figure simply the from the current Samp output? A bit like I did for the interaction_intra_influ output, which is essentially the same as the 'simple' influ output. In principle intersecting Samp with tree/intra should do nothing more than increase the CI around the estimates compared to the basic version where you only look at Samp. 

I suppose this all depends a little bit on what you think of as the 'main' uncertainty and what as the secondary one that it interacts with, and I may be revealing here my bias in thinking immediately from a Samp-perspective, but in principle this should work, I guess? 

In theory we could even have two ways of visualising it, from both 'main' uncertainties. 

Let's not worry about speed now. It's going to take forever, but we warn people and they can run on a cluster if they think it's too much (+ the cool parallel processing in the future).

**Comment by gijsbertwerner** [comment]
On a related note, you are not yet working on the main samp interactions, right @caterinap ? I couldn't find at least, but may have missed. I am asking because I thought I'd work the rest of today, and must admit I have lost track a bit of who's working on what.

**Comment by caterinap** [comment]
hehe I know how you feel! I am currently doing the tree_clade interactions, so feel free to do the samp_ones!
Or if you prefer the the intra_clade one is also missing.

**Comment by gijsbertwerner** [comment]
Ok, cool. Will get started with Samp in a separate branch I think :-)

**Comment by caterinap** [comment]
> In theory we could even have two ways of visualising it, from both 'main' uncertainties.

That is what I did for intra_tree interaction where you can choose to plot all uncertainties, only intra, or only tree (see here: https://github.com/paternogbc/sensiPhy/pull/143).

But to disentangle the two you would need a nested loop (see also issue #142 (5th comment)), which complicates a bit the code.

**Comment by caterinap** [comment]
we are discussing that also in issue #145. I am still not sure what is the best solution :)

**Comment by gijsbertwerner** [comment]
Yes, let's discuss tomorrow! I am actually using nested loops in my implementations of intra_samp and intra_influ, although what I have done so far with the summary methods does't direclty allow the user to disentangle (they could still do it manually, I suppose, with the raw outputs). I suppose we don't really want to make things too difficult either in the visualisation options, given that our target users are primarily people without a great deal of experience.
