### ISSUE TITLE
samp_gls: pval not found

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#15]
Need to fix this error.

**Comment by caterinap** [comment]
In vari_pgls this error is linked to the convergence problem in gls, the model does not converge so there is no pval. I have to fix this too. Probably put the "try" in a different way.

**Comment by paternogbc** [comment]
This problem is not occuring any more in samp_gls, I am not sure why. Do you still have this error in vari_pgls?

**Comment by caterinap** [comment]
I think it depends on the dataset and its size, I think that putting the "try" at the beginning of my loop might solve the problem... I'll test it and keep you updated

**Comment by caterinap** [comment]
Actually I was wondering why you used Try instead of TryCatch?

**Comment by paternogbc** [comment]
I far as I understand, try is just a simple version of TryCatch. Because the situation is very simple, I am using try. We need to decide on that and to update all function to similar error syntax. If you think TryCatch is a better call, we can use that in all functions.

**Comment by caterinap** [comment]
New gls error that seems linked to the convergence one (http://grokbase.com/t/r/r-sig-phylo/121d63rda3/lambda-pic-vs-pgls): 
Error in eigen(val) : infinite or missing values in 'x'

**Comment by gijsbertwerner** [comment]
Should be solved now with new samp_phylolm
