### ISSUE TITLE
Error to fix before v0.7

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#153]
Hey Guys, just created  this issue focused on the errors we find during testing of the master branch so we can easialy keep track and work together to find adequate solutions.

**Comment by paternogbc** [comment]
__tree_clade_phyglm:__ example not working

```
# Simulate Data:
set.seed(6987)
mphy = rmtree(150, N = 30)
x = rTrait(n=1,phy=mphy[[1]])
X = cbind(rep(1,150),x)
y = rbinTrait(n=1,phy=mphy[[1]], beta=c(-1,0.5), alpha=.7 ,X=X)
cla <- rep(c("A","B","C","D","E"), each = 30)
dat = data.frame(y, x, cla)
# Run sensitivity analysis:
clade <- tree_clade_phyglm(y ~ x, phy = mphy, data = dat, 
                           n.tree = 3, n.sim = 5, clade.col = "cla")
# To check summary results and most influential clades:
summary(clade)
# Visual diagnostics for clade removal:
sensi_plot(clade)
# Specify which clade removal to plot:
sensi_plot(clade, "B")
sensi_plot(clade, "C")
sensi_plot(clade, "D") #The clade with the largest effect on slope and intercept

## End(Not run)
```

**Error**  
```
Used dataset has  150  species that match data and phylogeny



Error in tree_clade_phyglm(y ~ x, phy = mphy, data = dat, n.tree = 3,  : 
  object 'model' not found
```

**Comment by caterinap** [comment]
Problem solved in commit  c64e990

**Comment by gijsbertwerner** [comment]
Sounds good!

**Comment by paternogbc** [comment]
**tree_xxx_phylm  and intra_xxx_phylm functions**

Fixed problems introduced by __progressbar__:

Solution:
Loop only between trees (on tree_xxx functions) to avoid miss counting with recombine.

**Comment by paternogbc** [comment]
***clade_phylm*** broken graph (probably after standardization of slope ->   @@estimate)

```
library(sensiPhy)
data(primates)
fit <- clade_phylm(log(sexMaturity) ~ log(adultMass), phy = primates$phy[[1]], 
                   data = primates$data, clade.col = "family", times = 50)
sensi_plot(fit, clade = "Cercopithecidae")
sensi_plot(fit, clade = "Cebidae") 
sensi_plot(fit)
```
## Error
> Warning: Ignoring unknown aesthetics: estimate
 Show Traceback
   Rerun with Debug
   Error: geom_abline requires the following missing aesthetics: slope

**Comment by paternogbc** [comment]
Hey @caterinap,

could you please check this Error from the `intra_clade_phylm()` help example:

```
set.seed(6987)
phy = rtree(100)
x = rTrait(n=1,phy=phy,parameters=list(ancestral.state=2,optimal.value=2,sigma2=1,alpha=1))
X = cbind(rep(1,100),x)
y = rbinTrait(n=1,phy=phy, beta=c(-1,0.5), alpha=.7 ,X=X)
z = rnorm(n = length(x),mean = mean(x),sd = 0.1*mean(x))
cla <- rep(c("A","B","C","D"), each = 25)
dat = data.frame(y, x, z, cla)
intra_clade <- intra_clade_phyglm(formula=y ~ x, data = dat, phy = phy,
                                  clade.col = "cla", n.sim = 30, n.intra = 3,
                                  y.transf = log, Vx = "z", distrib="normal")
```
# Error

```
Error in intra_clade_phyglm(formula = y ~ x, data = dat, phy = phy, clade.col = "cla",  : 
  object 'data_phy' not found
In addition: Warning message:
In intra_clade_phyglm(formula = y ~ x, data = dat, phy = phy, clade.col = "cla",  :
  distrib=normal: make sure that standard deviation is provided for Vx
```

**Comment by paternogbc** [comment]
**tree_influ_tree()**
summary() stats problem. The average values presented do not match manual calculations using the raw data. Must be some error in calculation of the average (estimate, DIFest, estimate.perc, etc) probably around aggregate function within the `summary` method ('summary.sensiTree_Influ'). It seems unlikely that the raw calculations are wrong because they come from the original influ_function.  
Find error and test possible solutions.

IF you have any idea @caterinap ? I am checking the code carefully but could not find the problem yet.

**Comment by caterinap** [comment]
Concerning: **tree_influ_tree() summary() stats problem**
I cannot find the problem, when I calculate manually from raw I find the same results given by summary.

**Comment by paternogbc** [comment]
@caterinap I fixed the problem. in this commit : https://github.com/paternogbc/sensiPhy/commit/b477513fb0bb23be8e34569dde3551b83f4d1fe8

Replaced this:
```
rows.estimate <- match(names(sp.estimate), sensi.estimates$species)
``` 
by this:
```
rows.estimate <- sensi.estimates$species %in% sp.estimate.tab$`Species removed`
```

I left the original code there so we look later also. 
I think the rows.estimate was cropping more then it should on the previous code. 
So the average values were not equal. Now I think it is all good. If you also checked and found no problems.

**Comment by gijsbertwerner** [comment]
For some reason `tree_samp_phyglm` seems not to be exported properly. I received the error `could not find function "tree_samp_phyglm"`, but don't fully understand why because everything seems well in the R folder.

**Comment by gijsbertwerner** [comment]
When running the example tree_intra_phylm seems to run into troubles. It completes all the simulations and then ends with this warning: `Error in data.frame(iteration = N, do.call("rbind", x)) : 
  arguments imply differing number of rows: 910, 100
In addition: Warning messages:`

Seems to be there is something wrong at the stage of combining the simulations. I haven't figured out why yet, but have to run in a minute so thought I'd just drop here, in case anybody wants to have a look already.

**Comment by paternogbc** [comment]
@caterinap and @gijsbertwerner, sorry but I agree with Cat, this issue went out of control hahaha. So lets make individual issues even for small problems we find from now on. If you spot something just open a issue with the example and tag people you think might have a clue. This will help to keep track and also to avoid this mess. (sorry it was a bad idea).

**Comment by gijsbertwerner** [comment]
Yes, agreed! Sorry this became such a mess! I think I may have created this problem in the first place :-( Sorry! Let's close.
