### ISSUE TITLE
verbose = FALSE

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#156]
@caterinap hey Cat,

Could you please check if this argument (VERBOSE) still functional across the package?  
Because I think it was related to the progressbar, issue right? If it is the case we should remove from all functions. Otherwise we could chat about so I can understand. =)

**Comment by caterinap** [comment]
Verbose is to silent the match_data_phy function in the iterations (otherwise it would print the information about number of matching species/tips n times)
