### ISSUE TITLE
Problem in recombine function

### ISSUE THREAD

**Issue by caterinap** [paternogbc/sensiPhy#159]
I was trying to find out why intra_influ_phyglm was giving errors when I found that the problem was coming from `recombine`. The issue was that when using  `n.rows<- nrow(x[[1]])` it was assuming that all the elements in the list had the same dimension. But this is not always the case, for instance when a model does not converge and the iteration is skipped. So I changed it in a way that it can rbind datasets of different numbers of rows and it works fine. But then I found a second problem. When the list was like that:

![image](https://user-images.githubusercontent.com/6351295/29722146-f87045c4-89bf-11e7-89e1-4e6a6902c071.png)

Recombine was giving this:
![image](https://user-images.githubusercontent.com/6351295/29722351-a9579ca2-89c0-11e7-920f-b02883d992c5.png)

So, the information about the iteration was not correct and the information on intercept/predictor was lost. So I modified it (commit bee4d76) and the output is now:

![image](https://user-images.githubusercontent.com/6351295/29722421-fb0799da-89c0-11e7-8a7c-77a8b07ed04a.png)

But it means that we need to revise all `summary `of interaction functions because they are probably broken! This might also explain the weird things in your plots @paternogbc (but I am not sure). Very bad: this weekend I am at a wedding (again!) and cannot work on this :(

NB: I also changed `list `into `sensi.list` to avoid to use a function name as argument (commit 46b5224)

**Comment by paternogbc** [comment]
Hey @caterinap thanks a lot for finding and fixing this problem. I will see and fix the broken summary methods tomorrow. But I guess it won't be too much work. And let's make more tests to be sure recombine is working well on all other cases :)

**Comment by paternogbc** [comment]
Checking functions for summary / sensi_plot problems.
`tree_influ_phylm`: __OK__
`tree_influ_phyglm`: __OK__
