### ISSUE TITLE
CRAN check: v0.7

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#161]
Heys guys, I have solved most of the things.
These still missing to be solved. Just keeping track.

````r
Undocumented arguments in documentation object 'intra_clade_phyglm'
  ‘Vy’ ‘y.transf’ ‘model’

Documented arguments not in \usage in documentation object 'intra_samp_phyglm':
  ‘model’ ‘y.transf’

Undocumented arguments in documentation object 'intra_samp_phylm'
  ‘Vy’

Undocumented arguments in documentation object 'sensi_plot.influ.physig'
  ‘...’

Undocumented arguments in documentation object 'sensi_plot.sensiIntra_Clade'
  ‘graphs’

Documented arguments not in \usage in documentation object 'sensi_plot.sensiIntra_Influ':
  ‘param’

Documented arguments not in \usage in documentation object 'sensi_plot.sensiIntra_Samp':
  ‘param’

Undocumented arguments in documentation object 'sensi_plot.sensiTree_Clade'
  ‘graphs’

Documented arguments not in \usage in documentation object 'sensi_plot.sensiTree_Influ':
  ‘param’

Undocumented arguments in documentation object 'tree_intra_phyglm'
  ‘btol’
Documented arguments not in \usage in documentation object 'tree_intra_phyglm':
  ‘Vy’ ‘model’
```

**Comment by caterinap** [comment]
Ok are you working on it now? If not, I'm on it!

**Comment by paternogbc** [comment]
I have just pushed some changes.
would go back to that later. But if you can go on it would be great! ;)

It would be good to run checks also in your computer and see if something else show up.
Then update here =)

Thanks

**Comment by caterinap** [comment]
All good (fixed commit ee0127c).
Concerning the check I still have two `warnings ` that will be fixed when you will rebuild the documentation. No errrors but 1 note:
```
checking package dependencies ... NOTE
Package suggested but not available for checking: 'rmarkdown'
```

**Comment by paternogbc** [comment]
You are right!

![deepinscreenshot_20170902000707](https://user-images.githubusercontent.com/9639481/29973403-c2fb8ec2-8f72-11e7-9170-9932bc44119f.png)

@caterinap and @gijsbertwerner could you please run CRAN checks on your computers, after updating R and Rstudio to the last version, and report the results here?
Also, could you please add the details of your system ('field using plataform') from the output.
```
* using platform: x86_64-pc-linux-gnu (64-bit)
```

**Comment by caterinap** [comment]
Sure! Can you just push the new documentation to master so we are all on the same page?

**Comment by paternogbc** [comment]
sorry. it is update now =)

**Comment by caterinap** [comment]
**SUCCESS**!! But I still have the same NOTE.
```
* using R version 3.4.1 (2017-06-30)
* using platform: x86_64-w64-mingw32 (64-bit)
```
![image](https://user-images.githubusercontent.com/6351295/29974393-ff498220-8f32-11e7-9acb-ef94e2fc9066.png)

**Comment by caterinap** [comment]
**SUCCESS!**
```
* using R version 3.4.1 (2017-06-30)
* using platform: x86_64-w64-mingw32 (64-bit)
```
![image](https://user-images.githubusercontent.com/6351295/29975034-3ff0cd40-8f35-11e7-8354-8115628c9e08.png)

(some examples are still a bit long to run, we could reduce the number of iterations but I guess it's also ok as it is)

Well done everybody 🥇

**Comment by gijsbertwerner** [comment]
Running mine now!

---------------------------------------------------
Dr. Gijsbert Werner
Newton Fellow, Department of Zoology
Junior Research Fellow, Balliol College
University of Oxford

Balliol College
Broad Street
Oxford
OX1 3BJ
United Kingdom




On 1 Sep 2017, at 15:48, Caterina Penone <notifications@github.com<mailto:notifications@github.com>> wrote:


SUCCESS!

* using R version 3.4.1 (2017-06-30)
* using platform: x86_64-w64-mingw32 (64-bit)


[image]<https://user-images.githubusercontent.com/6351295/29975034-3ff0cd40-8f35-11e7-8354-8115628c9e08.png>

(some examples are still a bit long to run, we could reduce the number of iterations but I guess it's also ok as it is)

Well done everybody 🥇

**Comment by gijsbertwerner** [comment]
YES SUCCESS TOO!!!!!

* checking examples ... OK
Examples with CPU or elapsed time > 5s
                      user system elapsed
intra_influ_phylm  107.006  4.280 112.820
intra_influ_phyglm  69.325  6.005  77.204
tree_influ_phyglm   52.054  4.749  57.760
tree_influ_phylm    45.965  2.202  50.341
intra_clade_phyglm  40.507  3.445  44.514
intra_clade_phylm   39.797  1.771  45.600
tree_intra_phyglm   22.436  1.878  24.800
tree_samp_phyglm    20.575  1.984  24.104
intra_samp_phyglm   19.896  1.766  22.114
tree_samp_phylm     15.648  0.760  16.792
samp_physig         12.313  0.483  12.936
intra_samp_phylm    11.557  0.479  12.177
influ_phyglm        11.123  0.823  12.282
influ_physig        10.657  0.431  11.379
tree_physig         10.176  0.394  10.629
intra_physig         9.664  0.378  10.192
tree_intra_phylm     8.816  0.334   9.265
tree_phyglm          6.243  0.529   6.866
samp_phyglm          4.687  0.418   5.240
* DONE

Status: OK

R CMD check results
0 errors | 0 warnings | 0 notes

My computer is clearly quite a bit slower than yours, Caterina, but this is my slow laptop so no worries.

Systems stuff:

* using R version 3.4.1 (2017-06-30)
* using platform: x86_64-apple-darwin15.6.0 (64-bit)

We did it!!!

---------------------------------------------------
Dr. Gijsbert Werner
Newton Fellow, Department of Zoology
Junior Research Fellow, Balliol College
University of Oxford

Balliol College
Broad Street
Oxford
OX1 3BJ
United Kingdom




On 1 Sep 2017, at 15:48, Caterina Penone <notifications@github.com<mailto:notifications@github.com>> wrote:


SUCCESS!

* using R version 3.4.1 (2017-06-30)
* using platform: x86_64-w64-mingw32 (64-bit)


[image]<https://user-images.githubusercontent.com/6351295/29975034-3ff0cd40-8f35-11e7-8354-8115628c9e08.png>

(some examples are still a bit long to run, we could reduce the number of iterations but I guess it's also ok as it is)

Well done everybody 🥇

**Comment by paternogbc** [comment]
Very nice guys =) 
It is wierd but TRAVIS still gives the following error:
```
checking PDF version of manual without hyperrefs or index ... ERRORchecking PDF version of manual ... WARNING
LaTeX errors when creating PDF version.
This typically indicates Rd problems.
LaTeX errors found:
! LaTeX Error: Something's wrong--perhaps a missing \item.
See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
```

**Comment by caterinap** [comment]
Looks that you fixed it! Well done!

**Comment by paternogbc** [comment]
There still some small problems with CRAN check. I am not sure if it is system dependent or something else, but working on it. But I should finish today together with the online tutorial.
Then you can have a look on that before I submit the manuscript =) Lets say tonight or Tuesday morning!

**Comment by paternogbc** [comment]
Found the problem! =) Submitting to CRAN right now.
