### ISSUE TITLE
Trait evolution (discrete and continuous) improvements/issues

### ISSUE THREAD

**Issue by gijsbertwerner** [paternogbc/sensiPhy#164]
Just for my/our benefit, and as a place for a quick note to not forget, have started this issue.

**Comment by gijsbertwerner** [comment]
Issues with clade_Discrete I am now aware of:

- Even though fitDiscrete takes a vector, and not a data frame (see my previous remark on tree_Discrete in: https://github.com/paternogbc/sensiPhy/issues/162), for clade-functions we need a second column to keep track of what clade/grouping each species belongs to. I don't really see how we can avoid this, so have rebuild (compared to tree_Discrete) a bit, so that we are in fact feeding a data frame here. This is not consistent with the other xx_Discrete functions, but wil have to do for now, I think.

**Comment by gijsbertwerner** [comment]
There is no visualisation yet for this. We could repurpose the one for clade_phylm etc., but would be pretty difficult. I am leaving this for now, since the summary works fine and that is key, and suggest we only implement this is if we have time.

**Comment by caterinap** [comment]
Checked (Caterina):

- [ ] tree_Discrete
- [ ] tree_Continuous
- [ ] clade_Discrete
- [ ] clade_Continuous
- [ ] influ_Discrete
- [ ] influ_Continuous
- [ ] samp_Discrete
- [ ] samp_Continuous

Some things I changed while debugging (I will keep updating this):
- moved `sensi_plot.sensiInflu.TraitEvol` from file `sensi_plot.sensiIntra.sensiTree.R` to file `sensi_plot.sensiInflu.R`

Some other things to discuss (I will keep updating this):
- fitDiscrete throws [this type](https://www.mail-archive.com/r-sig-phylo@r-project.org/msg03642.html) of warnings when track=TRUE - one possibility would be to silent them but it's a bit dangerous. For instance this happens in the example given in the help:
```
tree_binary_lambda<-tree_discrete(data = adultMass_binary,phy = primates$phy,
model = "SYM",transform = "lambda",n.tree = 30,track = T)
```

**Comment by gijsbertwerner** [comment]
Yes, good point on the warnings, Caterina. I have generally not really done too much with any warnings any of the trait-evolution throw (another one you often get is optimisation parameters hitting their bounds), other than just printing them back to the user. 

I am a bit of two minds on what to do with this. In principle I feel this is typically a result from the underlying methods, and if the users are using that, they should understand what is going on and deal with it at that level. Also relevant is this issue: https://github.com/paternogbc/sensiPhy/issues/168 For that reason, I would say that silencing might be a bit too risky? 

But, let's certainly pick 'clean' examples that run without too many error messages from the underlying implementation !

**Comment by paternogbc** [comment]
I also agree for now (it is safer). 
Later we can discuss about warnings and try to find a more elegant solution.

**Comment by gijsbertwerner** [comment]
Influ_continuous issue should now be finished, see: https://github.com/paternogbc/sensiPhy/issues/171

**Comment by caterinap** [comment]
works nicely now!
