### ISSUE TITLE
No intra_Discrete/Continuous functions. Why?

### ISSUE THREAD

**Issue by gijsbertwerner** [paternogbc/sensiPhy#166]
I have decide not to implement any intra_Discrere/Continuous functions. 

The reason for this in the case of Continuous is that fitContinouos in geiger already implements the option to specify an SE column, i.e. it does exactly what intra_cont would do. So there is no point in redoing it. 

For Discrete it just doesn't really make sense given our current set-up of intr_xx, given that you need an SE column and discrete data don't really have any. I suppose that in principle you could use some simulation approach to resimlate binary/categorical data as well (in fact, I have some ideas for this as a future sensiPhy implementation), but for now it's just too different an idea and would be confusing in the same function, I think.

Just putting it here, so you'll know!

**Comment by caterinap** [comment]
sounds good to me!
