### ISSUE TITLE
Evaluate fitDiscrete/Continuous own error checking

### ISSUE THREAD

**Issue by gijsbertwerner** [paternogbc/sensiPhy#168]
Both fitDiscrete/Continuous do some checking for things like convergence. This is currently not evaluated in our functions. It might be wise to evaluate this to catch potential errors (additionally to the try-error catch we already do). Note to self to consider this.

**Comment by paternogbc** [comment]
CRAN tests of the branch, just putting errors here as self reminder.

``` r
> #Load data:
> data("primates")
> #Model trait evolution accounting for phylogenetic uncertainty
> clade_cont<-clade_continuous(data=primates$data,phy = primates$phy[[1]],model="OU",
+ trait.col = "adultMass",clade.col="family",n.sim=30,n.species=10,track=TRUE)
Error in .check_ncores(cores) : 8 simultaneous processes spawned
Calls: clade_continuous ... <Anonymous> -> fxopt -> <Anonymous> -> .check_ncores
Execution halted
````

**Comment by gijsbertwerner** [comment]
Will close for now, we can always do this in a new iteration :-)
