### ISSUE TITLE
influ_continuous/discrete

### ISSUE THREAD

**Issue by gijsbertwerner** [paternogbc/sensiPhy#171]
The sensi_plot functions for influ_discrete/influ_continuous are pretty basic now. Essentially they plot histograms of the key parameters of interest (transition rates for discrete, sigsq for continuous, aicc and optpar for both), but they don't label species of interest/outliers as in the 'main' influ_phy(g)lm functions (but a bit similar to influ_physig). 

Since users can easily get this key info from a summary() call, and compare with the figure, I would propose to not implement this for now, unless we really feel bored (unlikely!). Let's leave as a future enhancement.

**Comment by paternogbc** [comment]
Yep sure, lets keep the graphs simple, summary tables gives all the crucial information.

@gijsbertwerner, I was testing `influ_continuous` and found the following error:

``` r
#Load data:
data("primates")
#Model trait evolution accounting for phylogenetic uncertainty
adultMass<-primates$data$adultMass
names(adultMass)<-rownames(primates$data)
influ_cont<-influ_continuous(data = adultMass,phy = primates$phy[[1]],
                             model = "OU",cutoff = 2,track = T)
```

> **Error** in influ_continuous(data = adultMass, phy = primates$phy[[1]], model = "OU",  : 
  object 'sDIFoptpar' not found

**Comment by gijsbertwerner** [comment]
Thanks Gustavo, working on it now!

**Comment by paternogbc** [comment]
Thanks, @gijsbertwerner!
checked and working very well! ;)
