### ISSUE TITLE
Some more changes (sorry!)

### ISSUE THREAD

**Issue by gijsbertwerner** [paternogbc/sensiPhy#178]
While going over the package one last time, I am running into a few minor things and have made changes. I know this means we'll have to rerun the manuals etc., @paternogbc . Sorry! Just thought I'd maintain a list of changes I have made for our records.

-  clade_cont/clade_discrete had n.sim=1 for the first example for both. I think this is to limit the time for the CRAN checks. For the ones which are in the 'not-run' part which should not be tested anyway (right), but are shown to the end-user, I have again increased this to n=20, because otherwise looks weird. 
- clade_cont/clade_discrete had an error in the output for full estimates (the optpar was printed twice).
- Minor typos in clade_cont/clade_discrete
- I discovered that summary calls for both clade_cont/clade_discrete give an error when the optpar is against the bounds. This makes sense, and should probably a warning for the user. We can write a better loop to catch and process this later. 
- I rephrased some of the language describing the output to influe_cont/discrete, to be more accurate. 
- The @return bit from Samp_continuous/discrete still contained some errors from being copied from other helps. Now solved. 
- In the tree_continuous/discrete too there were examples visible to the end-user with n.tree = 1 or 2. I have changed these to 30, because I think these are not being run by CRAN anyway and otherwise they just look really weird to the user. 

Ok, done now I think (with the exception of the bit below)!

**Comment by gijsbertwerner** [comment]
Stuff to do still:

- Include links to the sense_plots for the new traitevol methods (most are written already) into the general sensi_plot help pag.

**Comment by paternogbc** [comment]
Hey @gijsbertwerner that is great! Thanks. Yep, the code with n.tree = 1 is to pass Cran tests. 
\dontshow are executed by CRAN but not shown to users. 
\dontrun are shown but not executed. 

So we always want to run at least one test of the function (to be sure it is not broken), but this needs to be faster then 5 sec. 

Regarding the other changes, excellent! And no worries about re-building stuff, it is great to know we cleared small typo/bugs  =)

**Comment by gijsbertwerner** [comment]
Great, makes sense, Gustavo! I figured that that's what it would work like. 

I can do the sensi_plot methods update tomorrow, but am afraid superbusy today.

**Comment by paternogbc** [comment]
@gijsbertwerner, I can do it no worries. I will try to submit the package tonight (Aussie time).

Cheers!

**Comment by gijsbertwerner** [comment]
Cool, I have added the help for sensi_plot.sensiSamp.TraitEvol now in https://github.com/paternogbc/sensiPhy/commit/76e5f0ee031d5d83a9a03f7249223b05e5f5637e

**Comment by paternogbc** [comment]
Perfect, all done then!
