### ISSUE TITLE
Small suggested change in tutorial

### ISSUE THREAD

**Issue by gijsbertwerner** [paternogbc/sensiPhy#179]
In the samp_discrete example, I really like what is now the second example in the help function for samp_binary, i.e. an ARD rather than a symmetrical model, because the nice result there is that the one transition rate (q12) is not very sensitive, but the other is supersensitive. Thought that might make a nicer example for the tutorial than the a bit boring symmetrical one we are now using?

**Comment by gijsbertwerner** [comment]
The same applies to the clade_discrete example. Perhaps more fun to use the ARD example online, because it nicely shows a difference between the two transitions rates with one (almost) significantly affected and the other not. 

BTW, I would change this myself, but I am afraid I have to admit I don't know how to put the figures in in tutorials :-(

**Comment by paternogbc** [comment]
thanks @gijsbertwerner I will do that.

**Comment by gijsbertwerner** [comment]
Great, thanks, Gustavo! Yes, if you set model = "ER" or "SYM" the q12 and q21 should be exactly the same, because you then essentially assume that the gain rate is exactly the same as the loss rate. So this is a good test to see if it actually works as it should (which I think it does). 

ER and SYM behave exactly the same, because currently xx_discrete only accepts binary traits and not categorical states with more trait values. For a binary state ER and SYM are effectively the same, if/when we at some point expand to also allow for multi-state categorical states these will start to behave differently.

**Comment by paternogbc** [comment]
Hey @gijsbertwerner, Thanks for the clarification ;)
