### ISSUE TITLE
samp_ANOVA & samp_ANCOVA

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#18]
I am having problems to built these functions. Because the X variable is categorical you cannot exclude species at random. If you do so, at some point you will exclude all values from one of the categories and the analysis will not run. So, how do you think we should proceed? I can exclude the same number of points from each category. But also, at some point there will be a problem because the data might have unbalanced design where some treatments have less data than others. This problem will increase if the categorical variable has lots of levels.  Any Ideias?

**Comment by caterinap** [comment]
Maybe remove the a proportional amount of species on each category.. I mean if you have 100 species A and 200 species B and you remove 10% of data, then you remove 10 species A and 20 species B.

**Comment by paternogbc** [comment]
Yeap, I will give a try. However, we need to think some way to stop removing points when you reach a minimal number of species for the category with less data.
