### ISSUE TITLE
Correlation structure

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#19]
At the moment we are using corPagel from `ape` package as the standard correlation structure. However, it would be interesting to let the user choose which correlation structure he desires to use. For instance, these other correlation structures are also available in `ape`: 
corBlomberg; corBrownian; corGrafen; corMartins.

It would be nice to find a solution to include the type of correlation structure as an argument for samp_pgls, influ_pgls and varPgls. This is not so easy because we need to transform a character value into a function to run the proper `ape` function before fiting the models. I am not sure if this is a priority, but if we find an easy solution, then I think we should definitely include this feature in the package.

**Comment by caterinap** [comment]
AGREE!

**Comment by gijsbertwerner** [comment]
I guess this is also no longer relevant since we use phylolm as the basis for the pgls, which already implements various evolutionary models.
