### ISSUE TITLE
CRAN_check_01

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#21]
Status: 3 WARNINGs, 2 NOTEs

* checking R code for possible problems ... NOTE
sensi_plot: no visible global function definition for ‘aes’
sensi_plot: no visible binding for global variable ‘n.percents’
sensi_plot: no visible binding for global variable ‘beta.class’
sensi_plot: no visible global function definition for ‘geom_point’
sensi_plot: no visible global function definition for
  ‘scale_x_continuous’
sensi_plot: no visible global function definition for ‘ylab’
sensi_plot: no visible global function definition for ‘xlab’
sensi_plot: no visible global function definition for
  ‘scale_colour_manual’
sensi_plot: no visible global function definition for ‘geom_hline’
sensi_plot: no visible global function definition for ‘theme’
sensi_plot: no visible global function definition for ‘element_text’
sensi_plot: no visible global function definition for ‘unit’
sensi_plot: no visible global function definition for ‘element_rect’
sensi_plot: no visible binding for global variable ‘power.beta’
sensi_plot: no visible binding for global variable ‘percent_sp_removed’
sensi_plot: no visible global function definition for
  ‘scale_y_continuous’
sensi_plot: no visible global function definition for ‘geom_line’
sensi_plot: no visible global function definition for ‘n’
sensi_plot: no visible global function definition for ‘ggplot’
sensi_plot: no visible binding for global variable ‘proportion’
sensi_plot: no visible global function definition for ‘geom_bar’
sensi_plot: no visible global function definition for
  ‘scale_fill_manual’
sensi_plot: no visible binding for global variable ‘DFbeta’
sensi_plot: no visible binding for global variable ‘mDFbetas’
sensi_plot: no visible global function definition for ‘geom_errorbar’
sensi_plot: no visible binding for global variable ‘..density..’
sensi_plot: no visible global function definition for ‘geom_histogram’
sensi_plot: no visible global function definition for ‘geom_density’
sensi_plot: no visible global function definition for ‘geom_vline’
sensi_plot: no visible binding for global variable ‘intercept’
sensi_plot: no visible binding for global variable ‘sDFbeta’
sensi_plot: no visible global function definition for
  ‘scale_colour_gradient’
sensi_plot: no visible global function definition for ‘element_blank’
sensi_plot: no visible global function definition for ‘ggtitle’
variPgls: no visible global function definition for ‘is.rooted’
variPgls: no visible binding for global variable ‘force.root’

* checking Rd line widths ... NOTE
Rd file 'samp_phyloglm.Rd':
  \examples lines wider than 100 characters:
     shorebird.data$Egg.Mass.binary<-ifelse(shorebird.data$Egg.Mass>30,1,0) #Turn egg mass into a binary variable
     samp_phyloglm1<-samp_phyloglm(formula = Egg.Mass.binary~M.Mass,data = shorebird.data,phy=shorebird.tree,btol = 50)

Rd file 'variPgls.Rd':
  \examples lines wider than 100 characters:
     variPgls(resp=Ly,pred=Lx$xmean,vari.pred=Lx$xse,tree=multitree,ntree=2,nvari=2,method="normal",taxa.nam=sp)

These lines will be truncated in the PDF manual.
* checking Rd cross-references ... WARNING
Missing link or links in documentation object 'samp_phyloglm.Rd':
  ‘pgls’

See section 'Cross-references' in the 'Writing R Extensions' manual.

* checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'influ_phyloglm'
  ‘formula’ ‘data’ ‘phy’ ‘btol’

Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.

* checking PDF version of manual ... WARNING
LaTeX errors when creating PDF version.
This typically indicates Rd problems.

**Comment by paternogbc** [comment]
All Errors were fixed!
Only warnings and NOTES needs to be adressed.

Also, aditional tests in Windows and Mac should be performed.

**Comment by paternogbc** [comment]
all notes and warnings are ok!

**Comment by gijsbertwerner** [comment]
Great, wonderful!! 

Talk to you both tomorrow! 

---------------------------------------------------
Gijsbert Werner MSc
Department of Ecological Science
Faculty of Earth and Life Sciences
Vrije Universiteit Amsterdam
De Boelelaan 1085
1081 HV Amsterdam
The Netherlands
+31-(0)20-5987085

----- Original Message -----
