### ISSUE TITLE
Package Documentation

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#22]
1. Packages vignettes
 * Introduction to sensiPhy
 * How to contribute with sensiPhy (based on ggplot2) 
2. wiki page
 * Why use sensiPhy?
 * How to support sensiPhy?
 * How to install?
 * Become a member
 * How to cite?
 * Quick tutorial

**Comment by paternogbc** [comment]
### To organize and standardize (functions):
~~help files~~
~~examples~~

**Comment by gijsbertwerner** [comment]
Help / examples will still need to be standardised for the plotting functions and/or the vari function, I guess. I can probably give that a start but may need some help.

**Comment by paternogbc** [comment]
Ok I will try to write a first version of the help files an then you can cross-check the details.

**Comment by gijsbertwerner** [comment]
Perfect!



Op 7 jul. 2015 om 16:50 heeft Gustavo Paterno <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Ok I will try to write a first version of the help files an then you can cross-check the details.

**Comment by paternogbc** [comment]
Help file for sensi_plot is done:
https://github.com/paternogbc/sensiPhy/blob/master/R/sensi_plot.R

I dont think we need help files for the subfunctions because they are not going to be exported.
