### ISSUE TITLE
Function to non-randomly subsample your species/dataset. 

### ISSUE THREAD

**Issue by gijsbertwerner** [paternogbc/sensiPhy#29]
It would be nice to have at some point function were subsampling is not random, but biased. 

This is something you can use if you know that your dataset is biased, e.g. in the case that you study a binary trait and you have more 1’s in your dataset that you know are out there. Then, when subsampling you could preferentially drop more 1’s than 0 to ‘balance’ the dataset more and see how that affects your conclusions. I have once done something along these lines, and could take a look. Probably more something for the (distant) future than to focus on now.

**Comment by paternogbc** [comment]
Yep, that sounds interesting! I have implemented also a subsampling bias related not to the data but to the phylogeny. So you could exclude species based on their phylogenetic relateness. In these cases, the subsampling could favor the exclusion of more related species where the exclusion probability would be a function of the mean pair-wise phylogenetic distance. This was is pointed in issue #4 . I think we should keep both approaches in mind.
