### ISSUE TITLE
update and fix variPgls

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#30]
We need: 

~~1. replace `nlme::gls` function by `phylolm::phylolm` to fit the models (check if this fix the false convergence error). If this fix the error, then:~~
 
2. split variPgls in two functions:  ???
__intra_phylolm__: to consider intra-specific variation   
__tree_phylolm__: to consider phylogenetic uncertainty

3. Build new graph function to plot the results:
__plot_intra_phylolm__
__plot_tree_phylolm__

4. Standardize code and help files.

**Comment by caterinap** [comment]
vari_phylolm is working now! no more convergence problem with phylolm - working on plot_vari_phylolm now, do you still prefer split it in two functions?

**Comment by paternogbc** [comment]
Great news!

**Comment by paternogbc** [comment]
So Gijsbert, what do you think: should we split vari_phylolm ?

Caterina, How much work it would take? If is not so much, I think we should split the in two functions. OI can also help you on this task. We can also split the work =)

**Comment by paternogbc** [comment]
Well done =)
