### ISSUE TITLE
glm for tree and intra + more graphs?

### ISSUE THREAD

**Issue by caterinap** [paternogbc/sensiPhy#39]
Hi,
I splitted vari and cleaned *tree* and intra *phylolm*. Do we want the *glm* version of these functions?
I also added the graphic function for the 2 functions (*plot_tree.intra_phylolm.R*), the name is not very nice, feel free to change it :)
Below an example of the graphic output, any suggestion is welcome:

![tree vari_phylolm](https://cloud.githubusercontent.com/assets/6351295/9155766/b1400660-3ec3-11e5-88e0-ff7f2e80b64e.png)

Cheers,

caterina

**Comment by paternogbc** [comment]
Ohh Cat! great! that is very nice!

I think it would be very nice to include the tree_phyloglm and intra_phyloglm... I will also include the clade_phyloglm. I think is not going to be much work. But we can also do this later. 
I like the graphs! The blue line is the slope +- sd or 95% CI? 

Is this real data?, the variation in the slope is huge!

**Comment by caterinap** [comment]
OK, I'll add the glm then!
The blue line is +-sd (it is written somewhere in the graph function description) and yes.. it is real data! It is the invasive dataset (body mass ~ geo range) with *intra_phylolm*. The huge variation is probably due to the two species with large body mass and/or geo range. I should probably do an *influ_phylolm* on it ;-)

**Comment by paternogbc** [comment]
Nice!

Ok, great! 
Maybe you can use __log10__ in one or both variables to make this difference smaller. ;)
cheers!

**Comment by paternogbc** [comment]
About the graphs, I would use circles instead and white background so they match the others graphs... =)

**Comment by caterinap** [comment]
Everything done!
(the graph was already using **log** =) )
