### ISSUE TITLE
CRAn tests:

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#41]
remember to fix these warnings:

intra_phylolm : funr: no visible global function definition for 'rnorm'
intra_phylolm : funr: no visible global function definition for 'runif'
intra_phylolm : <anonymous>: no visible global function definition for
  'runif'
intra_phylolm: no visible binding for global variable 'sd'
plot_tree.intra_phylolm: no visible binding for global variable
  'formula'
plot_tree.intra_phylolm: no visible binding for global variable 'slope'
plot_tree.intra_phylolm: no visible binding for global variable
  '..density..'
plot_tree.intra_phylolm: no visible binding for global variable
  'intercept'
plot_tree.intra_phylolm: no visible binding for global variable
  'predictor'
plot_tree.intra_phylolm: no visible binding for global variable
  'response'
plot_tree.intra_phylolm: no visible global function definition for
  'scale_color_manual'
plot_tree.intra_phylolm: no visible binding for global variable 's3'
tree_phylolm: no visible binding for global variable 'sd'

**Comment by caterinap** [comment]
ok, thanks

**Comment by paternogbc** [comment]
kkk that was a self comment.. dont need to worry about these now.. 
I am used to solve then ;) Is just to organize the to-do list for later.. I wont be able to do ir now... 
cheers,
Guga

**Comment by caterinap** [comment]
It is ok, I am already doing this while building the logistic version of the functions :)

**Comment by paternogbc** [comment]
You can see when there is a problem building the package, when the badge at the initial page of the repository shows: build = failing or error. Every time we push anything to master it runs all cran tests and send the results by e-mail.. plus update the badge status... So, when is not passing, it means that if we install the package from the github it will fail to install on the local computer... its a great automatization!

**Comment by paternogbc** [comment]
the way to fix... is in here: http://stackoverflow.com/questions/31774258/ggplot2-inside-r-packages-notes-during-cran-tests

cheers!

**Comment by caterinap** [comment]
oh, cool, I'll look at the badge with more attention!
and now I understand the <- NULL in your plotting functions! kk

cheers!

**Comment by paternogbc** [comment]
Yep, this automatic tests are awesome! the NULL is a ugly hack. However, that is what people have recomended to solve these warnings from CRAN. So, lets keep it simple for now... =)

**Comment by caterinap** [comment]
Ok, now he should be happy but I still have to find a solution for:
plot_tree.intra_phylolm: no visible global function definition for ‘scale_color_manual’ (which should be in ggplo2)

**Comment by paternogbc** [comment]
yep... you need to include on the roxygen #' part of the code:
> @importFrom ggplot2 scale_color_manual aes etc
all functions from ggplot2 that you use on the code.

Plus, if you click on the badge it will take you to the last test. There you can search for "warnings" or "notes" to see the specific errors.

**Comment by paternogbc** [comment]
but, perhaps is better to: first update all your packages (specially: phylolm, ggplot2 and ape)

then.. run the test on your local machine with:
> devtools::dev_mod()
> devtools::check()

Then you can see all results on R studio. =)

**Comment by caterinap** [comment]
ok, now it should be ok, (I just need to push the glm versions to github once they are ready)

**Comment by caterinap** [comment]
We should test our Logistic functions to see if they work when the user has a formula like that:
> cbind(a,b) ~ d
And I also have to modify match_dataphy to support this type of imput...

**Comment by paternogbc** [comment]
True!! lets do that.

**Comment by paternogbc** [comment]
I fixed the problem with intra_phyloglm.
Now we need to check this warning:
> Undocumented code objects:
  ‘tree_phyloglm’

It is probably related to the help of the function. Perhaps a @param of the function is undocumented.

**Comment by caterinap** [comment]
The whole .Rd files for the new functions were missing. It is fixed now!

**Comment by paternogbc** [comment]
great!
