### ISSUE TITLE
datasets for the package

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#47]
We need to define the specific dataset for the package.

It will be more then one since the phylogeny is also a dataset.

For each we need to crop the full datset into a small data.frame containing only the variables that we use in the example. This is important because it is easier to document and also for the users to undertand the dataset. For the logistic regression whe can transform one continuous variable into binary based on percentis.

Cat, could you help with that? Afther we have the croped datsets I can then work on the documentation.
Ps. The phylogeny should match the croped dataset, so we dont have to crop the phylogeny on the examples. ;)

**Comment by caterinap** [comment]
Ok, no problem!

**Comment by paternogbc** [comment]
Nice!

The package is almost there! =)
I am working on the s3 methods, so all functions will work with summary and plot (instead of sensi_plot). 
This is simpler for the user.. we are used to summary and plot. ;)

**Comment by caterinap** [comment]
Great!!
Ok, my to do list is :
- include the match_dataphy function (from utilities) in all functions, I guess it is working fine.. at least I did not notice any bug lately
- adapt intra and tree phyloglm functions to receive c(a,b) data..

**Comment by paternogbc** [comment]
Nice...

Do you have the variables from the dataset that are good to use in the examples of in intra_ and tree_ ?
I want to put this together... so we need to define the same variables (I think) for all examples, then crop the phylogeny and dataset to this variables...

**Comment by caterinap** [comment]
I used body mass and geographic range. Are these the same variables you were planning to use? Is the new dataset working well with your functions? Otherwise I can adapt my example to the carnivore dataset (I have data on intraspecific variability for 97 carnivores).

**Comment by paternogbc** [comment]
Done! commit #97
