### ISSUE TITLE
In try, use `silent=FALSE` ?

### ISSUE THREAD

**Issue by caterinap** [paternogbc/sensiPhy#51]
It might be useful for the users to see the error messages from `phylolm::phylolm` or `phyloglm`.
I had a case where `btol` had to be lower than 50 otherwise the model was not working.
What do you think?

**Comment by paternogbc** [comment]
I think for the full model, yep. But for the simulations like in samp_xxx I am not so sure..

**Comment by caterinap** [comment]
Ok, I am going to change it in intra and phylo function.
Thanks!
