### ISSUE TITLE
Functions name?

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#54]
Hey Cat and Gijsbert,

I was wondering about the functions names.
What do you think about changing the names of our functions:

* samp_phylolm     ->   samp_phylm
* samp_phyloglm   ->   samp_phyglm
* influ_phylolm       ->   influ_phylm
* influ_phyloglm     ->   influ_phyglm

etc .....

Although the original names resamble the phylolm function, the names get very big

What do you think?

Cheers

**Comment by caterinap** [comment]
You are right, the names are a bit long. And if in future we make the functions work with other packages, this name is more general and will not need to be changed.
Approved! :)

**Comment by gijsbertwerner** [comment]
Yes, I agree, great idea! Both makes it shorter, and more general so it won't look too much as if we are only expanding on the phylolm package!





Op 28 aug. 2015 om 11:54 heeft Gustavo Paterno <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Hey Cat and Gijsbert,

I was wondering about the functions names.
What do you think about changing the names of our functions:

  *   samp_phylolm -> samp_phylm
  *   samp_phyloglm -> samp_phyglm
  *   influ_phylolm -> influ_phylm
  *   influ_phyloglm -> influ_phyglm

etc .....

Although the original names resamble the phylolm function, the names get very big

What do you think?

Cheers

**Comment by paternogbc** [comment]
Great!

so lets do this at the very end, then we dont make other problems to pop up. =)
After we finish everything I can change all names ;)

Super!
