### ISSUE TITLE
Error in plot()

### ISSUE THREAD

**Issue by caterinap** [paternogbc/sensiPhy#66]
When I plot a intra_phylm object I get this error:
`> plot(mods)`
`Error in xy.coords(x, y, xlabel, ylabel, log) : 
  'x' is a list, but does not have components 'x' and 'y'`
I am trying to figure out where is the problem.. any idea is welcome :)

**Comment by paternogbc** [comment]
Ok.. I will have a look!

cheers,
Guga

**Comment by caterinap** [comment]
Maybe it is linked to the fact that in phyloglm we have
`class(res) <- c("sensiClade","sensiCladeL")`
which is a list..?

**Comment by paternogbc** [comment]
You have to plot with sensi_plot(mods) not plot(mods). Or it was just a typo on your comment.

**Comment by caterinap** [comment]
Well, that was an easy issue to solve.. My bad!! 
Everything works fine with sensi_plot(mods)
thanks!!!

**Comment by paternogbc** [comment]
;))
happens all the time! It is just an outside perspective... Great job! ;)
