### ISSUE TITLE
intra_xxx: within species variation

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#79]
We need to point out that our randomization srategy fro intra_xxx, assumes that within species variation is similar between species and is random (not correlated with phylogeny). 

We should point that, if great intra-specific variation is found on the data and withins species variation is not constant across species, other methods should be used to properly account for this errors. (Refs from Moder PCM book).

**Comment by caterinap** [comment]
Good point! We should mention it in both in the vignette & the paper.
