### ISSUE TITLE
rownames data

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#86]
When there is no rownames in data our functions dont work because match_dataphy reports the following error:

Error in match_dataphy(formula.... ,  : 
  No tips are common to the dataset and phylogeny

I think we should suggest the user to check row names and make sure they match phylogeny tips instead of just stating that no tips are common to the datset and phylogeny. 

What do you think?

**Comment by caterinap** [comment]
I added this in match_dataphy:
stop("No tips are common to the dataset and phylogeny, 
        Please check if row names of your dataset contain species/tip names")

Is it enough?

**Comment by paternogbc** [comment]
Perfect! 

=))
