### ISSUE TITLE
Plot multiple clades for sensi_clade

### ISSUE THREAD

**Issue by caterinap** [paternogbc/sensiPhy#89]
Should we give the option to plot all clades in one unique plot? This might be useful to visualize the effect of each clade relative to the others. But it is not going to work when there are lots of them, maybe limit to 10?

**Comment by paternogbc** [comment]
i think this option would be very nice when comparing many clades.
Not sure how to implement that, but we can discuss for the next realse. 
Perhaps we can start a list for these "next release" improvements.

**Comment by gijsbertwerner** [comment]
I guess we are doing this now, right?
