### ISSUE TITLE
tree_phylm: check and print Error if times is > then # of trees

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#90]
When the number of trees in the multphylo object is smaller then the argument "times" we need to 
print an error, otherwise the user might get confused.

**Comment by caterinap** [comment]
good thought! should be quite easy to do. I can do it quickly, or you prefer to do it?

**Comment by paternogbc** [comment]
Yes please ;).
Could point the commit to this issue (#90).
Cheers,
